it_vacancies_dict = {
    "Аналитик": [
        "Аналитик данных",
        "Data Analyst",
        "BI аналитик",
        "Системный аналитик",
        "Бизнес-аналитик",
        "Product Analyst",
        "Аналитик требований",
        "Web аналитик",
        "Маркетинговый аналитик",
        "Финансовый аналитик",
        "Data Scientist",
        "Аналитик больших данных",
        "Big Data Analyst",
        "Аналитик ИБ",
        "SOC аналитик",
        "Аналитик компьютерного зрения",
    ],
    "Разработчик": [
        "Python разработчик",
        "Java разработчик",
        "JavaScript разработчик",
        "TypeScript разработчик",
        "C++ разработчик",
        "C# разработчик",
        ".NET разработчик",
        "Go разработчик",
        "PHP разработчик",
        "Ruby разработчик",
        "Scala разработчик",
        "Rust разработчик",
        "Kotlin разработчик",
        "Swift разработчик",
        "Frontend разработчик",
        "Backend разработчик",
        "Fullstack разработчик",
        "Web разработчик",
        "Мобильный разработчик",
        "iOS разработчик",
        "Android разработчик",
        "React разработчик",
        "Angular разработчик",
        "Vue разработчик",
        "Node.js разработчик",
        "Django разработчик",
        "Flask разработчик",
        "Spring разработчик",
        "1С разработчик",
        "Игровой разработчик",
        "Unity разработчик",
        "Unreal Engine разработчик",
        "Embedded разработчик",
        "Блокчейн разработчик",
        "Web3 разработчик",
        "DevOps разработчик",
        "Инженер по автоматизации",
    ],
    "Тестировщик": [
        "QA инженер",
        "Тестировщик ПО",
        "Software Tester",
        "QA автоматизатор",
        "Automation QA",
        "Ручной тестировщик",
        "Manual QA",
        "Инженер по тестированию",
        "Test Engineer",
        "Специалист по качеству",
        "Quality Assurance",
        "SDET",
        "Инженер по производительности",
        "Performance Engineer",
        "Нагрузочное тестирование",
    ],
    "Менеджер": [
        "IT Project Manager",
        "Project Manager",
        "Product Manager",
        "Product Owner",
        "IT менеджер",
        "Руководитель ИТ проектов",
        "Technical Lead",
        "Team Lead",
        "Руководитель разработки",
        "Development Manager",
        "Scrum мастер",
        "Scrum Master",
        "Agile коуч",
        "Agile Coach",
        "IT директор",
        "CIO",
        "CTO",
        "Delivery Manager",
        "Программный менеджер",
        "Program Manager",
        "Руководитель отдела разработки",
        "Head of Development",
        "AI Product Manager",
        "ML Product Manager",
    ],
    "DevOps и инфраструктура": [
        "DevOps инженер",
        "DevOps engineer",
        "Site Reliability Engineer",
        "SRE инженер",
        "Системный администратор",
        "System Administrator",
        "Системный инженер",
        "System Engineer",
        "Cloud инженер",
        "Cloud Engineer",
        "Platform Engineer",
        "Infrastructure Engineer",
        "Сетевой инженер",
        "Network Engineer",
        "Администратор Linux",
        "Linux Administrator",
        "Администратор Windows",
        "Windows Administrator",
        "Администратор баз данных",
        "Database Administrator",
        "Инженер по мониторингу",
        "Monitoring Engineer",
        "Middle инженер",
        "Специалист по автоматизации",
        "Automation Engineer",
        "MLOps инженер",
        "MLOps Engineer",
        "LLMOps инженер",
        "LLMOps Engineer",
    ],
    "Безопасность": [
        "Специалист по кибербезопасности",
        "Cybersecurity Specialist",
        "Аналитик информационной безопасности",
        "Information Security Analyst",
        "Инженер ИБ",
        "Information Security Engineer",
        "Специалист по защите информации",
        "InfoSec Specialist",
        "Пентестер",
        "Penetration Tester",
        "Этичный хакер",
        "Ethical Hacker",
        "SOC специалист",
        "Security Operations Center Analyst",
        "Специалист по криптографии",
        "Cryptography Specialist",
        "Аудитор ИБ",
        "Information Security Auditor",
        "Специалист по безопасности сетей",
        "Network Security Specialist",
        "Application Security Engineer",
        "GRC специалист",
        "AI Security Specialist",
        "ML Security Engineer",
    ],
    "Data Engineering": [
        "Инженер данных",
        "Data Engineer",
        "Big Data Engineer",
        "Специалист по ETL",
        "ETL разработчик",
        "Хранилище данных",
        "Data Warehouse Engineer",
        "Инженер аналитических систем",
        "Analytics Engineer",
        "Pipeline Engineer",
        "Специалист по DWH",
        "Feature Store Engineer",
    ],
    "Искусственный интеллект": [
        "Промпт инженер",
        "Prompt Engineer",
        "ИИ тренер",
        "AI Trainer",
        "ML инженер",
        "Machine Learning Engineer",
        "AI разработчик",
        "AI Developer",
        "Deep Learning инженер",
        "Deep Learning Engineer",
        "Computer Vision инженер",
        "Computer Vision Engineer",
        "NLP инженер",
        "Natural Language Processing Engineer",
        "LLM инженер",
        "Large Language Model Engineer",
        "Generative AI инженер",
        "GenAI Developer",
        "AI исследователь",
        "AI Researcher",
        "ML исследователь",
        "ML Researcher",
        "Специалист по нейросетям",
        "Neural Network Engineer",
        "AI Architect",
        "ML Architect",
        "AI Product Manager",
        "ML Product Manager",
        "AI аналитик",
        "AI Analyst",
        "ML Data Associate",
        "AI Quality Assurance",
        "ИИ тестировщик",
        "AI Tester",
        "RAG инженер",
        "RAG Engineer",
        "Fine-tuning инженер",
        "Fine-tuning Engineer",
        "AI Data Scientist",
        "Applied Scientist",
        "Research Scientist AI",
    ],
    "Технический специалист": [
        "Технический писатель",
        "Technical Writer",
        "IT рекрутер",
        "IT Recruiter",
        "Техническая поддержка",
        "Technical Support",
        "Support Engineer",
        "Системный архитектор",
        "System Architect",
        "Решение архитектор",
        "Solution Architect",
        "Enterprise архитектор",
        "Enterprise Architect",
        "ИТ консультант",
        "IT Consultant",
        "Специалист по внедрению",
        "Implementation Specialist",
    ],
    "Новые профессии": [
        "Специалист по виртуальной реальности",
        "VR специалист",
        "Специалист по дополненной реальности",
        "RPA специалист",
        "Robotic Process Automation",
        "DataOps инженер",
        "DataOps Engineer",
        "Квантовый программист",
        "Quantum Developer",
        "Web3 специалист",
        "Web3 Developer",
        "Блокчейн специалист",
        "Blockchain Developer",
        "Smart Contract Developer",
        "DeFi специалист",
        "Metaverse Developer",
    ],
}